application:
  business:
    transaction:
      max-amount: 1000
  transport:
    event-driven:
      kafka:
        client-id: antifraud-client-id
        groupd-id: antifraud-group-id
        broker: 'localhost:9092'
        initialRetryTime: 5000
        maxRetryTime: 5000
        retries: 10
        topics:
          antifraud-check: antifraud-check
          antifraud-analysis-response: antifraud-analysis-response
