application:
  transport:
    event-driven:
      kafka:
        client-id: transaction-client-id
        groupd-id: transaction-group-id
        broker: 'localhost:9092'
        topics:
          antifraud-check: antifraud-check
          antifraud-analysis-response: antifraud-analysis-response
